# Ruby CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
version: 2.1

executors:
  test_executor:
    parameters:
      ruby_version:
        type: string
      elasticsearch_version:
        type: string
        default: 6.8.9
    docker:
      - image: circleci/ruby:<< parameters.ruby_version >>
      - image: redis:3.2-alpine
      - image: docker.elastic.co/elasticsearch/elasticsearch:<< parameters.elasticsearch_version >>
        environment:
          - xpack.security.enabled: false
          - discovery.type: single-node
    working_directory: ~/app

jobs:
  build:
    parameters:
      ruby_version:
        type: string
      elasticsearch_version:
        type: string
        default: 6.8.9
    executor:
      name: test_executor
      ruby_version: << parameters.ruby_version >>
      elasticsearch_version: << parameters.elasticsearch_version >>
    steps:
      - checkout
      - run:
          name: Copying config files for Flickr and Instagram
          command: |
            cp -p config/flickr.yml.example config/flickr.yml
            cp -p config/instagram.yml.example config/instagram.yml
      - restore_cache:
          key: bundle-{{ checksum "Gemfile.lock" }}
      - run: gem install bundler:1.17.3
      - run:
          name: bundle install
          command: |
            bundle install --without development --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          key: bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/app/vendor/bundle
      - run:
          name: Install Code Climate Test Reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Waiting for Elasticsearch
          command: dockerize --wait http://localhost:9200 -timeout 1m
      - run:
          name: Running Tests
          environment:
            CC_TEST_REPORTER_ID: 0643ac526557dd490bc6f0542cac608a8815d7538dd580261e67dd334c07cc87
          command: |
            ./cc-test-reporter before-build
            bundle exec rspec spec --format progress --format RspecJunitFormatter -o ~/rspec/rspec.xml
            ./cc-test-reporter after-build
      - store_test_results:
          path: ~/rspec
      - store_artifacts:
          path: ~/rspec
          destination: ~/rspec

workflows:
  build_and_test:
    jobs:
      - build:
          matrix:
            parameters:
              ruby_version:
                - 2.5.5
                - 2.6.6
                - 2.7.3
              elasticsearch_version:
                - 6.8.9
                - 7.9.3
